package br.senac.flashfood.constants

enum class ExtraConstants(value: String) {
    RESTAURANT_ID("RESTAURANT_ID"),
    RESTAURANT_NAME("RESTAURANT_NAME"),
    RESTAURANT_DESC("RESTAURANT_DESC"),
    PRODUCT_ID("PRODUCT_ID"),
    PRODUCT_NAME("PRODUCT_NAME"),
    PRODUCT_DESC("PRODUCT_DESC"),
    PRODUCT_PRICE("PRODUCT_PRICE"),
    COD_PURCHASE("COD_PURCHASE"),
    TOTAL_VALUE_PURCHASE("TOTAL_VALUE_PURCHASE"),
    PURCHASE_DATE("PURCHASE_DATE");

    val value = value
}